---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: jay
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "jaypanchal14/spe-mini-project"
        source: pull
      register: pull_result

    - name: Display Docker Pull Result
      debug:
        var: pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name spe-container jaypanchal14/spe-mini-project